# Generated by Django 5.2.1 on 2025-05-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='link',
            new_name='linkGithub',
        ),
        migrations.AddField(
            model_name='projeto',
            name='linkProjeto',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
