# Generated by Django 5.2.1 on 2025-05-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_link_projeto_linkgithub_projeto_linkprojeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='linkGithub',
            field=models.URLField(blank=True, null=True),
        ),
    ]
